name: Docs Check
on:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    name: Mocks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install terraform-docs
        run: go install github.com/terraform-docs/terraform-docs@v0.19.0

      - name: Check doc updates were committed
        run: make docs check-clean
